
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.course
{
public sealed partial class Course : Luban.BeanBase
{
    public Course(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PreCourseIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PreCourseIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); NeedItemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NeedItemIds.Add(_e0);}}
        WasteTime = _buf.ReadInt();
        RecommendedPhysique = _buf.ReadInt();
        RecommendedIntelligence = _buf.ReadInt();
        PerLessonPhysique = _buf.ReadInt();
        PerLessonIntelligence = _buf.ReadInt();
        CompletionPhysique = _buf.ReadInt();
        CompletionIntelligence = _buf.ReadInt();
    }

    public static Course DeserializeCourse(ByteBuf _buf)
    {
        return new course.Course(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 前置课程
    /// </summary>
    public readonly System.Collections.Generic.List<int> PreCourseIds;
    public System.Collections.Generic.List<course.Course> PreCourseIds_Ref;
    /// <summary>
    /// 需要道具
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeedItemIds;
    public System.Collections.Generic.List<item.Item> NeedItemIds_Ref;
    /// <summary>
    /// 消耗时间
    /// </summary>
    public readonly int WasteTime;
    /// <summary>
    /// 推荐属性值
    /// </summary>
    public readonly int RecommendedPhysique;
    public readonly int RecommendedIntelligence;
    /// <summary>
    /// 每次学习增加属性
    /// </summary>
    public readonly int PerLessonPhysique;
    public readonly int PerLessonIntelligence;
    /// <summary>
    /// 完成课程增加属性
    /// </summary>
    public readonly int CompletionPhysique;
    public readonly int CompletionIntelligence;
   
    public const int __ID__ = -125350546;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PreCourseIds_Ref = new System.Collections.Generic.List<course.Course>();
        foreach (var _v in PreCourseIds) { PreCourseIds_Ref.Add(tables.TbCourse.GetOrDefault(_v)); }

        NeedItemIds_Ref = new System.Collections.Generic.List<item.Item>();
        foreach (var _v in NeedItemIds) { NeedItemIds_Ref.Add(tables.TbItem.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "preCourseIds:" + Luban.StringUtil.CollectionToString(PreCourseIds) + ","
        + "needItemIds:" + Luban.StringUtil.CollectionToString(NeedItemIds) + ","
        + "wasteTime:" + WasteTime + ","
        + "recommendedPhysique:" + RecommendedPhysique + ","
        + "recommendedIntelligence:" + RecommendedIntelligence + ","
        + "perLessonPhysique:" + PerLessonPhysique + ","
        + "perLessonIntelligence:" + PerLessonIntelligence + ","
        + "completionPhysique:" + CompletionPhysique + ","
        + "completionIntelligence:" + CompletionIntelligence + ","
        + "}";
    }
}
}

