
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.course
{
public partial class TbCourse
{
    private readonly System.Collections.Generic.Dictionary<int, course.Course> _dataMap;
    private readonly System.Collections.Generic.List<course.Course> _dataList;
    
    public TbCourse(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, course.Course>(n);
        _dataList = new System.Collections.Generic.List<course.Course>(n);
        for(int i = n ; i > 0 ; --i)
        {
            course.Course _v;
            _v = global::GameConfig.course.Course.DeserializeCourse(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, course.Course> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<course.Course> DataList => _dataList;

    public course.Course GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public course.Course Get(int key) => _dataMap[key];
    public course.Course this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

