
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class DialogueRow : Luban.BeanBase
{
    public DialogueRow(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Type = (DialogueType)_buf.ReadInt();
        Speaker = _buf.ReadString();
        Text = _buf.ReadString();
        NextId = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Choices = new System.Collections.Generic.List<DialogueChoice>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DialogueChoice _e0;  _e0 = global::GameConfig.DialogueChoice.DeserializeDialogueChoice(_buf); Choices.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Parameters = new System.Collections.Generic.List<DialogueParameter>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DialogueParameter _e0;  _e0 = global::GameConfig.DialogueParameter.DeserializeDialogueParameter(_buf); Parameters.Add(_e0);}}
    }

    public static DialogueRow DeserializeDialogueRow(ByteBuf _buf)
    {
        return new DialogueRow(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly DialogueType Type;
    /// <summary>
    /// 说话方
    /// </summary>
    public readonly string Speaker;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// 普通节点的下一个节点
    /// </summary>
    public readonly string NextId;
    /// <summary>
    /// 选项节点
    /// </summary>
    public readonly System.Collections.Generic.List<DialogueChoice> Choices;
    /// <summary>
    /// 条件或命令参数
    /// </summary>
    public readonly System.Collections.Generic.List<DialogueParameter> Parameters;
   
    public const int __ID__ = 1711448258;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "speaker:" + Speaker + ","
        + "text:" + Text + ","
        + "nextId:" + NextId + ","
        + "choices:" + Luban.StringUtil.CollectionToString(Choices) + ","
        + "parameters:" + Luban.StringUtil.CollectionToString(Parameters) + ","
        + "}";
    }
}
}

