
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct DialogueParameter
{
    public DialogueParameter(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Value = _buf.ReadString();
    }

    public static DialogueParameter DeserializeDialogueParameter(ByteBuf _buf)
    {
        return new DialogueParameter(_buf);
    }

    public readonly string Key;
    public readonly string Value;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

