
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 对话类型
    /// </summary>
    [System.Flags]
    public enum DialogueType
    {
        Line = 0,
        Choice = 1,
        Condition = 2,
        Command = 3,
        Jump = 4,
        End = 5,
    }

} 

