
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct DialogueChoice
{
    public DialogueChoice(ByteBuf _buf) 
    {
        Text = _buf.ReadString();
        NextId = _buf.ReadString();
    }

    public static DialogueChoice DeserializeDialogueChoice(ByteBuf _buf)
    {
        return new DialogueChoice(_buf);
    }

    public readonly string Text;
    public readonly string NextId;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Text:" + Text + ","
        + "NextId:" + NextId + ","
        + "}";
    }
}
}

