
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class EffectRow : Luban.BeanBase
{
    public EffectRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NextId = _buf.ReadInt();
        Desc = _buf.ReadString();
        Type = (EffectActionType)_buf.ReadInt();
        {int __n0 = _buf.ReadSize(); ActionParamInt = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActionParamInt[__index0] = __e0;}}
        {int __n0 = _buf.ReadSize(); ActionParamStr = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); ActionParamStr[__index0] = __e0;}}
    }

    public static EffectRow DeserializeEffectRow(ByteBuf _buf)
    {
        return new EffectRow(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 下一个id
    /// </summary>
    public readonly int NextId;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly EffectActionType Type;
    /// <summary>
    /// 操作参数
    /// </summary>
    public readonly int[] ActionParamInt;
    /// <summary>
    /// 操作参数
    /// </summary>
    public readonly string[] ActionParamStr;
   
    public const int __ID__ = 535294569;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nextId:" + NextId + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "actionParamInt:" + Luban.StringUtil.CollectionToString(ActionParamInt) + ","
        + "actionParamStr:" + Luban.StringUtil.CollectionToString(ActionParamStr) + ","
        + "}";
    }
}
}

