
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 效果行为类型
    /// </summary>
    [System.Flags]
    public enum EffectActionType
    {
        None = 0,
        /// <summary>
        /// 对话
        /// </summary>
        Dialogue = 1,
    }

} 

