
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class EventRow : Luban.BeanBase
{
    public EventRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Type = (GameEventType)_buf.ReadInt();
        {int __n0 = _buf.ReadSize(); ActionParamInt = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActionParamInt[__index0] = __e0;}}
        {int n0 = _buf.ReadSize(); NeedItemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NeedItemIds.Add(_e0);}}
        WasteTime = _buf.ReadInt();
        RecommendedPhysique = _buf.ReadInt();
        RecommendedIntelligence = _buf.ReadInt();
        PerLessonPhysique = _buf.ReadInt();
        PerLessonIntelligence = _buf.ReadInt();
        CompletionPhysique = _buf.ReadInt();
        CompletionIntelligence = _buf.ReadInt();
    }

    public static EventRow DeserializeEventRow(ByteBuf _buf)
    {
        return new EventRow(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly GameEventType Type;
    /// <summary>
    /// 操作参数
    /// </summary>
    public readonly int[] ActionParamInt;
    /// <summary>
    /// 需要道具
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeedItemIds;
    public System.Collections.Generic.List<ItemRow> NeedItemIds_Ref;
    /// <summary>
    /// 消耗时间
    /// </summary>
    public readonly int WasteTime;
    /// <summary>
    /// 推荐属性值
    /// </summary>
    public readonly int RecommendedPhysique;
    public readonly int RecommendedIntelligence;
    /// <summary>
    /// 每次学习增加属性
    /// </summary>
    public readonly int PerLessonPhysique;
    public readonly int PerLessonIntelligence;
    /// <summary>
    /// 完成增加属性
    /// </summary>
    public readonly int CompletionPhysique;
    public readonly int CompletionIntelligence;
   
    public const int __ID__ = 342750464;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NeedItemIds_Ref = new System.Collections.Generic.List<ItemRow>();
        foreach (var _v in NeedItemIds) { NeedItemIds_Ref.Add(tables.TbItem.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "actionParamInt:" + Luban.StringUtil.CollectionToString(ActionParamInt) + ","
        + "needItemIds:" + Luban.StringUtil.CollectionToString(NeedItemIds) + ","
        + "wasteTime:" + WasteTime + ","
        + "recommendedPhysique:" + RecommendedPhysique + ","
        + "recommendedIntelligence:" + RecommendedIntelligence + ","
        + "perLessonPhysique:" + PerLessonPhysique + ","
        + "perLessonIntelligence:" + PerLessonIntelligence + ","
        + "completionPhysique:" + CompletionPhysique + ","
        + "completionIntelligence:" + CompletionIntelligence + ","
        + "}";
    }
}
}

