
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GameplayGraphTriggerRow : Luban.BeanBase
{
    public GameplayGraphTriggerRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        TriggerType = (GameplayGraphTriggerType)_buf.ReadInt();
        TriggerKey = _buf.ReadString();
        GraphId = _buf.ReadInt();
        GraphId_Ref = null;
    }

    public static GameplayGraphTriggerRow DeserializeGameplayGraphTriggerRow(ByteBuf _buf)
    {
        return new GameplayGraphTriggerRow(_buf);
    }

    /// <summary>
    /// 触发器ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 事件类型
    /// </summary>
    public readonly GameplayGraphTriggerType TriggerType;
    /// <summary>
    /// 事件过滤Key；*表示不过滤
    /// </summary>
    public readonly string TriggerKey;
    /// <summary>
    /// 启动的流程
    /// </summary>
    public readonly int GraphId;
    public GameplayGraphRow GraphId_Ref;
   
    public const int __ID__ = -439847478;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        GraphId_Ref = tables.TbGameplayGraph.GetOrDefault(GraphId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "triggerType:" + TriggerType + ","
        + "triggerKey:" + TriggerKey + ","
        + "graphId:" + GraphId + ","
        + "}";
    }
}
}

