
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 游戏逻辑节点类型
    /// </summary>
    public enum GameplayNodeType
    {
        Root = 0,
        /// <summary>
        /// 播放对话
        /// </summary>
        Dialogue = 1,
        /// <summary>
        /// 显示选项
        /// </summary>
        Choice = 2,
        /// <summary>
        /// 结束
        /// </summary>
        End = 100,
    }

} 

