
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 游戏逻辑图触发事件类型
    /// </summary>
    public enum GameplayGraphTriggerType
    {
        /// <summary>
        /// 自定义事件
        /// </summary>
        Custom = 0,
        /// <summary>
        /// 购买道具
        /// </summary>
        ItemPurchased = 1,
        /// <summary>
        /// 击败怪物
        /// </summary>
        MonsterDefeated = 2,
        /// <summary>
        /// 与NPC交互
        /// </summary>
        NpcInteracted = 3,
        /// <summary>
        /// 进入区域
        /// </summary>
        AreaEntered = 4,
        /// <summary>
        /// 任务状态变化
        /// </summary>
        QuestStateChanged = 5,
    }

} 

