
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 游戏事件类型
    /// </summary>
    [System.Flags]
    public enum GameEventType
    {
        None = 0,
        /// <summary>
        /// 课程
        /// </summary>
        Course = 1,
    }

} 

