
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GameplayNodeRow : Luban.BeanBase
{
    public GameplayNodeRow(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        GraphId = _buf.ReadInt();
        GraphId_Ref = null;
        Desc = _buf.ReadString();
        Type = (GameplayNodeType)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); NextId = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); NextId.Add(_e0);}}
        DialogueSpeaker = _buf.ReadString();
        DialogueText = _buf.ReadString();
        {int n0 = _buf.ReadSize(); DialogueChoices = new System.Collections.Generic.List<DialogueChoice>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DialogueChoice _e0;  _e0 = global::GameConfig.DialogueChoice.DeserializeDialogueChoice(_buf); DialogueChoices.Add(_e0);}}
    }

    public static GameplayNodeRow DeserializeGameplayNodeRow(ByteBuf _buf)
    {
        return new GameplayNodeRow(_buf);
    }

    /// <summary>
    /// 全局唯一节点ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属流程
    /// </summary>
    public readonly int GraphId;
    public GameplayGraphRow GraphId_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 节点类型
    /// </summary>
    public readonly GameplayNodeType Type;
    /// <summary>
    /// 出口
    /// </summary>
    public readonly System.Collections.Generic.List<string> NextId;
    /// <summary>
    /// 说话方
    /// </summary>
    public readonly string DialogueSpeaker;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly string DialogueText;
    /// <summary>
    /// 选项节点
    /// </summary>
    public readonly System.Collections.Generic.List<DialogueChoice> DialogueChoices;
   
    public const int __ID__ = 1936353106;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        GraphId_Ref = tables.TbGameplayGraph.GetOrDefault(GraphId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "graphId:" + GraphId + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "nextId:" + Luban.StringUtil.CollectionToString(NextId) + ","
        + "dialogueSpeaker:" + DialogueSpeaker + ","
        + "dialogueText:" + DialogueText + ","
        + "dialogueChoices:" + Luban.StringUtil.CollectionToString(DialogueChoices) + ","
        + "}";
    }
}
}

