
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GameplayGraphRow : Luban.BeanBase
{
    public GameplayGraphRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        RootNodeId = _buf.ReadString();
    }

    public static GameplayGraphRow DeserializeGameplayGraphRow(ByteBuf _buf)
    {
        return new GameplayGraphRow(_buf);
    }

    /// <summary>
    /// 流程ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 策划说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 入口节点ID
    /// </summary>
    public readonly string RootNodeId;
   
    public const int __ID__ = -1124923886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "rootNodeId:" + RootNodeId + ","
        + "}";
    }
}
}

