
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ItemRow : Luban.BeanBase
{
    public ItemRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Actor = _buf.ReadString();
        Satiety = _buf.ReadInt();
    }

    public static ItemRow DeserializeItemRow(ByteBuf _buf)
    {
        return new ItemRow(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly string Actor;
    /// <summary>
    /// 饱腹
    /// </summary>
    public readonly int Satiety;
   
    public const int __ID__ = -514121305;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "actor:" + Actor + ","
        + "satiety:" + Satiety + ","
        + "}";
    }
}
}

