
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public course.TbCourse TbCourse {get; }
    public global.TbGlobal TbGlobal {get; }
    public item.TbItem TbItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCourse = new course.TbCourse(loader("course_tbcourse"));
        TbGlobal = new global.TbGlobal(loader("global_tbglobal"));
        TbItem = new item.TbItem(loader("item_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCourse.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
