
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TbEffect TbEffect {get; }
    public TbEvent TbEvent {get; }
    public TbGlobal TbGlobal {get; }
    public TbItem TbItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbEffect = new TbEffect(loader("tbeffect"));
        TbEvent = new TbEvent(loader("tbevent"));
        TbGlobal = new TbGlobal(loader("tbglobal"));
        TbItem = new TbItem(loader("tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbEffect.ResolveRef(this);
        TbEvent.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
