
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TbGameplayGraph TbGameplayGraph {get; }
    public TbGameplayNode TbGameplayNode {get; }
    public TbGameplayGraphTrigger TbGameplayGraphTrigger {get; }
    public TbGlobal TbGlobal {get; }
    public TbItem TbItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGameplayGraph = new TbGameplayGraph(loader("tbgameplaygraph"));
        TbGameplayNode = new TbGameplayNode(loader("tbgameplaynode"));
        TbGameplayGraphTrigger = new TbGameplayGraphTrigger(loader("tbgameplaygraphtrigger"));
        TbGlobal = new TbGlobal(loader("tbglobal"));
        TbItem = new TbItem(loader("tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameplayGraph.ResolveRef(this);
        TbGameplayNode.ResolveRef(this);
        TbGameplayGraphTrigger.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
