
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbDialogue
{
    private readonly System.Collections.Generic.Dictionary<int, DialogueRow> _dataMap;
    private readonly System.Collections.Generic.List<DialogueRow> _dataList;
    
    public TbDialogue(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogueRow>(n);
        _dataList = new System.Collections.Generic.List<DialogueRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DialogueRow _v;
            _v = global::GameConfig.DialogueRow.DeserializeDialogueRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DialogueRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DialogueRow> DataList => _dataList;

    public DialogueRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DialogueRow Get(int key) => _dataMap[key];
    public DialogueRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

