
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbEffect
{
    private readonly System.Collections.Generic.Dictionary<int, EffectRow> _dataMap;
    private readonly System.Collections.Generic.List<EffectRow> _dataList;
    
    public TbEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EffectRow>(n);
        _dataList = new System.Collections.Generic.List<EffectRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EffectRow _v;
            _v = global::GameConfig.EffectRow.DeserializeEffectRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EffectRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EffectRow> DataList => _dataList;

    public EffectRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EffectRow Get(int key) => _dataMap[key];
    public EffectRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

