
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbGameplayNode
{
    private readonly System.Collections.Generic.Dictionary<string, GameplayNodeRow> _dataMap;
    private readonly System.Collections.Generic.List<GameplayNodeRow> _dataList;
    
    public TbGameplayNode(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, GameplayNodeRow>(n);
        _dataList = new System.Collections.Generic.List<GameplayNodeRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameplayNodeRow _v;
            _v = global::GameConfig.GameplayNodeRow.DeserializeGameplayNodeRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, GameplayNodeRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameplayNodeRow> DataList => _dataList;

    public GameplayNodeRow GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameplayNodeRow Get(string key) => _dataMap[key];
    public GameplayNodeRow this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

