
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbGameplayGraph
{
    private readonly System.Collections.Generic.Dictionary<int, GameplayGraphRow> _dataMap;
    private readonly System.Collections.Generic.List<GameplayGraphRow> _dataList;
    
    public TbGameplayGraph(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GameplayGraphRow>(n);
        _dataList = new System.Collections.Generic.List<GameplayGraphRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameplayGraphRow _v;
            _v = global::GameConfig.GameplayGraphRow.DeserializeGameplayGraphRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, GameplayGraphRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameplayGraphRow> DataList => _dataList;

    public GameplayGraphRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameplayGraphRow Get(int key) => _dataMap[key];
    public GameplayGraphRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

