
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbGameplayGraphTrigger
{
    private readonly System.Collections.Generic.Dictionary<int, GameplayGraphTriggerRow> _dataMap;
    private readonly System.Collections.Generic.List<GameplayGraphTriggerRow> _dataList;
    
    public TbGameplayGraphTrigger(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GameplayGraphTriggerRow>(n);
        _dataList = new System.Collections.Generic.List<GameplayGraphTriggerRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameplayGraphTriggerRow _v;
            _v = global::GameConfig.GameplayGraphTriggerRow.DeserializeGameplayGraphTriggerRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, GameplayGraphTriggerRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameplayGraphTriggerRow> DataList => _dataList;

    public GameplayGraphTriggerRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameplayGraphTriggerRow Get(int key) => _dataMap[key];
    public GameplayGraphTriggerRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

