
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbGlobal
{

     private readonly GlobalRow _data;

     public GlobalRow Data => _data;

    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.GlobalRow.DeserializeGlobalRow(_buf);
    }


    /// <summary>
    /// 最大背包容量
    /// </summary>
     public int MaxBagNum => _data.MaxBagNum;
    /// <summary>
    /// 最大体力
    /// </summary>
     public int MaxStamina => _data.MaxStamina;
    /// <summary>
    /// 最大压力
    /// </summary>
     public int MaxStress => _data.MaxStress;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

