
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, ItemRow> _dataMap;
    private readonly System.Collections.Generic.List<ItemRow> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemRow>(n);
        _dataList = new System.Collections.Generic.List<ItemRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ItemRow _v;
            _v = global::GameConfig.ItemRow.DeserializeItemRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ItemRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ItemRow> DataList => _dataList;

    public ItemRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemRow Get(int key) => _dataMap[key];
    public ItemRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

