
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.global
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        MaxBagNum = _buf.ReadInt();
        MaxStamina = _buf.ReadInt();
        MaxStress = _buf.ReadInt();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new global.Global(_buf);
    }

    /// <summary>
    /// 最大背包容量
    /// </summary>
    public readonly int MaxBagNum;
    /// <summary>
    /// 最大体力
    /// </summary>
    public readonly int MaxStamina;
    /// <summary>
    /// 最大压力
    /// </summary>
    public readonly int MaxStress;
   
    public const int __ID__ = 1250542702;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MaxBagNum:" + MaxBagNum + ","
        + "MaxStamina:" + MaxStamina + ","
        + "MaxStress:" + MaxStress + ","
        + "}";
    }
}
}

