
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.global
{
public partial class TbGlobal
{

     private readonly global.Global _data;

     public global.Global Data => _data;

    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.global.Global.DeserializeGlobal(_buf);
    }


    /// <summary>
    /// 最大背包容量
    /// </summary>
     public int MaxBagNum => _data.MaxBagNum;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

