
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.game_event
{
public partial class TbGameEvent
{
    private readonly System.Collections.Generic.Dictionary<int, game_event.GameEvent> _dataMap;
    private readonly System.Collections.Generic.List<game_event.GameEvent> _dataList;
    
    public TbGameEvent(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, game_event.GameEvent>(n);
        _dataList = new System.Collections.Generic.List<game_event.GameEvent>(n);
        for(int i = n ; i > 0 ; --i)
        {
            game_event.GameEvent _v;
            _v = global::GameConfig.game_event.GameEvent.DeserializeGameEvent(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, game_event.GameEvent> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<game_event.GameEvent> DataList => _dataList;

    public game_event.GameEvent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game_event.GameEvent Get(int key) => _dataMap[key];
    public game_event.GameEvent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

